config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
     path('menu/', include('menu.urls')), 
]

home/urls.py
from unicodedata import name
from xml.etree.ElementInclude import include
from django.urls import path,include
from .views import IndexView, StoryView
from django.conf.urls.static import static
from django.conf import settings

app_name = 'home'

urlpatterns = [
    path('', IndexView.as_view(),name ='index'),
    path('story/',StoryView.as_view(),name="story")
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from .views import *

app_name = 'menu'

urlpatterns = [
    path('coffee/', CoffeeListView.as_view(), name='coffee'),
    path('beverage/', BeverageListView.as_view(), name='beverage'),
    path('desert/', DesertListView.as_view(), name='desert'),
    path('seasonmenu/', SeasonmenuListView.as_view(), name='seasonmenu'),
]

home/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Coffee(models.Model):
    title = models.CharField(max_length=100)
    sub_cate = models.CharField(max_length=100, default='')
    photo = models.ImageField(upload_to='coffee/%Y/%m/%d',default='coffee/no_image.png')
    desc = models.TextField()
    
    class Meta:
        ordering = ['title']
        
    def __str__(self):
        return self.title
    
    
class Beverage(models.Model):
    title = models.CharField(max_length=100)
    sub_cate = models.CharField(max_length=100, default='')
    photo = models.ImageField(upload_to='beverage/%Y/%m/%d',default='beverage/no_image.png')
    desc = models.TextField()
    
    class Meta:
        ordering = ['title']
        
    def __str__(self):
        return self.title
    
class Desert(models.Model):
    title = models.CharField(max_length=100)
    sub_cate = models.CharField(max_length=100, default='')
    photo = models.ImageField(upload_to='desert/%Y/%m/%d',default='desert/no_image.png')
    desc = models.TextField()
    
    class Meta:
        ordering = ['title']
        
    def __str__(self):
        return self.title
    
class SeasonMenu(models.Model):
    title = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='seasonmenu/%Y/%m/%d',default='seasonmenu/no_image.png')
    desc = models.TextField()
    
    class Meta:
        ordering = ['title']
        
    def __str__(self):
        return self.title

        
        

home/views.py
from pipes import Template
from re import template
from django.shortcuts import render
from django.views.generic import TemplateView

class IndexView(TemplateView):
    template_name= 'home/index.html'
    
class StoryView(TemplateView):
    template_name ='home/story.html'
    

# Create your views here.

menu/views.py
from pyexpat import model
from django.shortcuts import render
from django.views.generic import ListView
from .models import *

# Create your views here.
class CoffeeListView(ListView):
    model = Coffee
    template_name = 'menu/coffee.html'
    context_object_name = 'coffee_list'
    
class BeverageListView(ListView):
    model = Beverage 
    template_name = 'menu/beverage.html'
    context_object_name = 'beverage_list'
     
class DesertListView(ListView):
    model = Desert
    template_name = 'menu/desert.html'
    context_object_name = 'desert_list'
    
class SeasonmenuListView(ListView):
    model = SeasonMenu
    template_name = 'menu/seasonmenu.html'
    context_object_name = 'seasonmenu_list'

home/templates/home/index.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% load static %}

{% block header %}
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">MUHWA COFFEE</h1>
            <h2 class="masthead-subheading mb-0">THE BEST TASTE</h2>
        </div>
    </div>
</header>
{% endblock %}

{% block contents %}
 <!-- Content section 1-->
 <section id="scroll">
    <div class="container px-5 bg-light">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6 order-lg-2">
                <a href="{% url 'home:story' %}">
                    <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/01.jpg' %}" alt="..." />
                    </div>
                </a>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">감탄이 나오는 풍경</h2>
                    <p> 최고의 풍경을 자랑하는 커피숍입니다. 
                        햇빛이있는 낮이나 야경이 훤히보이는 밤 통창으로 아주 잘 느끼실수 있습니다. 
                        저희 커피숍에 매력이기도 하죠.</p>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Content section 2-->
<section>
    <div class="container px-5">
        <div class="row gx-5 align-items-center x">
            
            <div class="col-lg-6">
                <a href="{% url 'menu:coffee' %}">
                    <div class="p-5">
                        <img class="img-fluid rounded-circle" src="{% static 'img/main_header3.jpg' %}" alt="..." /></div>
                    </a>
            </div>
            
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4">따뜻한 커피</h2>
                    <p>따뜻한 커피와 함께 맜있는 빵. 편안하게 드시고 가실수 있습니다</p>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Content section 3-->
<section>
    <div class="container px-5 bg-light">
        <div class="row gx-5 align-items-center ">
            <div class="col-lg-6 order-lg-2">
                <a href="{% url 'menu:beverage' %}">
                    <div class="p-5">
                        <img class="img-fluid rounded-circle" src="{% static 'img/main_header4.jpg' %}" alt="..." />
                    </div>
                </a>
            </div>
            <div class="col-lg-6 order-lg-1">
                
                <div class="p-5">
                    <h2 class="display-4">시원한 음료</h2>
                    <p>만끽하실수 있는 시원한 음료</p>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Content section 4-->
<section>
    <div class="container px-5">
        <div class="row gx-5 align-items-center x">
            
            <div class="col-lg-6">
                <a href="{% url 'menu:desert' %}">
                    <div class="p-5">
                        <img class="img-fluid rounded-circle" src="{% static 'img/main_header3.jpg' %}" alt="..." /></div>
                    </a>
            </div>
            
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4">따뜻한 음식</h2>
                    <p>따뜻한 커피와 함께 맜있는 빵. 편안하게 드시고 가실수 있습니다</p>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Content section 5-->
<section>
    <div class="container px-5 bg-light">
        <div class="row gx-5 align-items-center ">
            <div class="col-lg-6 order-lg-2">
                <a href="{% url 'menu:seasonmenu' %}">
                    <div class="p-5">
                        <img class="img-fluid rounded-circle" src="{% static 'img/main_header4.jpg' %}" alt="..." />
                    </div>
                </a>
            </div>
            <div class="col-lg-6 order-lg-1">
                
                <div class="p-5">
                    <h2 class="display-4">계절을 빛내줄 시즌매뉴</h2>
                    <p>만끽하실수 있는 시원한 음료</p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

home/templates/home/story.html
{% extends 'base.html' %}

{% block title %}STORY{% endblock %}

{% load static %}

{% block contents %}
<div class="w-100">
    <img src="{% static 'img/story.jpg' %}" alt="" width="100%">
    <div class="position-absolute text-light top-50 translate-middle start-50 pt-10"><h1 style="font-size: 3em;">MUHWA STORY</h1>
    <p>
        <h2 style="letter-spacing: 0.2em;">
            커피를 만나다
        </h2>
        <h2>
            풍경을 만나다
        </h2>
        <h2>
            안녕하십니까
        </h2>
    </p>
    </div>
</div>

<div class="story-modal">

</div>

{% endblock %}

home/templates/menu/beverage.html
{% extends 'base.html' %}

{% block title %}-BEVERAGE{% endblock %}

{% block header %}
<div style="height:100px; background-color: #deb887;"></div>
{% endblock %}

{% block contents %}
<div style="background: #deb887 ;">
    <div class="container">
        <!-- <h2>BEVERAGE</h2> -->
        
        <div class="row">
            <h3>에이드</h3>
        {% for beverage in beverage_list %}
        {% if beverage.sub_cate == "에이드" %}
            <div class="col-6 col-md-3">
                <img src="{{beverage.photo.url}}" class="img-thumbnail" alt="">
                <p class="text-center">{{beverage.title}}</p>
            </div>
        {% endif %}
        {% endfor %}
        </div>
        
        <div class="row">
            <h3>차</h3>
        {% for beverage in beverage_list %}
        {% if beverage.sub_cate == "차" %}
            <div class="col-6 col-md-3">
                <img src="{{beverage.photo.url}}" class="img-thumbnail" alt="">
                <p class="text-center">{{beverage.title}}</p>
            </div>
        {% endif %}
        {% endfor %}
        </div>
    </div>

{% endblock %}

home/templates/menu/coffee.html
{% extends 'base.html' %}

{% block title %}-COFFEE{% endblock %}

{% block header %}
<div style="height:100px; background-color: #deb887;"></div>
{% endblock %}

{% block contents %}
<div style=" background:#deb887 ;">
    <div class="container">
        <!--<h2>COFFEE</h2>-->
    
        <div class="row">
            <h3>커피</h3>
            {% for coffee in coffee_list %}
            {% if coffee.sub_cate == '커피'%}
            <div class="col-6 col-md-3">
                <img src="{{coffee.photo.url}}" class="img-thumbnail" alt="">
                <p class="text-center">{{coffee.title}}</p>
                <!--<div>{{coffee.desc}}</div> -->
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <div class="row">
            <h3>콜드브루</h3>
            {% for coffee in coffee_list %}
            {% if coffee.sub_cate == '콜드브루'%}
            <div class="col-6 col-sm-3">
                <img src="{{coffee.photo.url}}" class="img-thumbnail" alt="">
                <p class="text-center">{{coffee.title}}</p>
                <!--<div>{{coffee.desc}}</div> -->
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <div class="row">
            <h3>핸드드립</h3>
            {% for coffee in coffee_list %}
            {% if coffee.sub_cate == '핸드드립'%}
            <div class="col-6 col-sm-3">
                <img src="{{coffee.photo.url}}" class="img-thumbnail" alt="">
                <p class="text-center">{{coffee.title}}</p>
                <!--<div>{{coffee.desc}}</div> -->
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

home/templates/menu/desert.html
{% extends 'base.html' %}

{% block title %}-DESERT{% endblock %}

{% block header %}
<div style="height:100px;  background:#deb887"></div>
{% endblock %}

{% block contents %}
<div style=" background:#deb887 ;">
    <div class="container">
        <div class="row">
            <h2>빵</h2>
            {% for desert in desert_list %}
            {% if desert.sub_cate == '빵'%}
            <div class="col-6 col-md-3">
                <img src="{{desert.photo.url}}" class="img-thumbnail" alt="">
                <p class="text-center">{{desert.title}}</p>
                <!--<div>{{desert.desc}}</div> -->
            </div>
            {% endif %}
            {% endfor %}
        </div>   
        <div class="row">
            <h2>케이크</h2>
            {% for desert in desert_list %}
            {% if desert.sub_cate == '케이크'%}
            <div class="col-6 col-md-3">
                <img src="{{desert.photo.url}}" class="img-thumbnail" alt="">
                <p class="text-center">{{desert.title}}</p>
                <!--<div>{{desert.desc}}</div> -->
            </div>
            {% endif %}
            {% endfor %}
        </div>    
    </div>
</div>

{% endblock %}

home/templates/menu/seasonmenu.html
{% extends 'base.html' %}

{% block title %}-SEASONMENU{% endblock %}

{% block header %}
<div style="height:100px;"></div>
{% endblock %}

{% block contents %}
<div class="container">
    <h2>SEASONMENU</h2>
    <div class="row">
    {% for seasonmenu in seasonmenu_list %}
        <div class="col-6 col-md-3">
            <img src="{{seasonmenu.photo.url}}" class="img-thumbnail" alt="">
            <p class="text-center">{{seasonmenu.title}}</p>
        </div>
    {% endfor %}
    </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>무화{% block title %}{% endblock %}</title>
        <!-- <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        Font Awesome icons (free version) -->
        {% load static %}
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'home:index' %}">MUHWA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'menu:coffee' %}">COFFEE</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'menu:beverage' %}">BVERAGE</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'menu:desert' %}">DESERT</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'menu:seasonmenu' %}">SEASONMENU</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'home:story' %}">STORY</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        {% block header %}
       
        {% endblock %}
        {% block contents %}
       
        {% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <!-- <script src="js/scripts.js"></script> -->
    </body>
</html>

templates/base1.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>무화{% block title %}{% endblock %}</title>
</head>
<body>
    {% block contents %}
    {% endblock %}
</body>
</html>